package com.demo.aml.mapper;

import com.demo.aml.pojo.T00JcsSql;
import com.demo.aml.pojo.T00JcsSqlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T00JcsSqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    long countByExample(T00JcsSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByExample(T00JcsSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByPrimaryKey(String jname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insert(T00JcsSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insertSelective(T00JcsSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    List<T00JcsSql> selectByExample(T00JcsSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    T00JcsSql selectByPrimaryKey(String jname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") T00JcsSql record, @Param("example") T00JcsSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExample(@Param("record") T00JcsSql record, @Param("example") T00JcsSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKeySelective(T00JcsSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_JCS_SQL
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKey(T00JcsSql record);
}