package com.demo.aml.mapper;

import com.demo.aml.pojo.T00Module;
import com.demo.aml.pojo.T00ModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T00ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    long countByExample(T00ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByExample(T00ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByPrimaryKey(String modulekey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insert(T00Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insertSelective(T00Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    List<T00Module> selectByExample(T00ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    T00Module selectByPrimaryKey(String modulekey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") T00Module record, @Param("example") T00ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExample(@Param("record") T00Module record, @Param("example") T00ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKeySelective(T00Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_MODULE
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKey(T00Module record);
}