package com.demo.aml.mapper;

import com.demo.aml.pojo.T00OperateLog;
import com.demo.aml.pojo.T00OperateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T00OperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_OPERATE_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    long countByExample(T00OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_OPERATE_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByExample(T00OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_OPERATE_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insert(T00OperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_OPERATE_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insertSelective(T00OperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_OPERATE_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    List<T00OperateLog> selectByExample(T00OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_OPERATE_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") T00OperateLog record, @Param("example") T00OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_OPERATE_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExample(@Param("record") T00OperateLog record, @Param("example") T00OperateLogExample example);
}