package com.demo.aml.mapper;

import com.demo.aml.pojo.T00RolePost;
import com.demo.aml.pojo.T00RolePostExample;
import com.demo.aml.pojo.T00RolePostKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T00RolePostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    long countByExample(T00RolePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByExample(T00RolePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByPrimaryKey(T00RolePostKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insert(T00RolePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insertSelective(T00RolePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    List<T00RolePost> selectByExample(T00RolePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    T00RolePost selectByPrimaryKey(T00RolePostKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") T00RolePost record, @Param("example") T00RolePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExample(@Param("record") T00RolePost record, @Param("example") T00RolePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKeySelective(T00RolePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ROLE_POST
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKey(T00RolePost record);
}