package com.demo.aml.mapper;

import com.demo.aml.pojo.T00SystemLog;
import com.demo.aml.pojo.T00SystemLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T00SystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    long countByExample(T00SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByExample(T00SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insert(T00SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insertSelective(T00SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    List<T00SystemLog> selectByExample(T00SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") T00SystemLog record, @Param("example") T00SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExample(@Param("record") T00SystemLog record, @Param("example") T00SystemLogExample example);
}