package com.demo.aml.mapper;

import com.demo.aml.pojo.T87OrganMap;
import com.demo.aml.pojo.T87OrganMapExample;
import com.demo.aml.pojo.T87OrganMapKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T87OrganMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    long countByExample(T87OrganMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByExample(T87OrganMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int deleteByPrimaryKey(T87OrganMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insert(T87OrganMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int insertSelective(T87OrganMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    List<T87OrganMap> selectByExample(T87OrganMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    T87OrganMap selectByPrimaryKey(T87OrganMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") T87OrganMap record, @Param("example") T87OrganMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByExample(@Param("record") T87OrganMap record, @Param("example") T87OrganMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKeySelective(T87OrganMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:52:49 CST 2018
     */
    int updateByPrimaryKey(T87OrganMap record);
}