package com.demo.aml.pojo;

public class T00ComAuth extends T00ComAuthKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_COM_AUTH.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_COM_AUTH.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_COM_AUTH.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_COM_AUTH.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_COM_AUTH.CREATEDATE
     *
     * @return the value of T00_COM_AUTH.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_COM_AUTH.CREATEDATE
     *
     * @param createdate the value for T00_COM_AUTH.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_COM_AUTH.CREATOR
     *
     * @return the value of T00_COM_AUTH.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_COM_AUTH.CREATOR
     *
     * @param creator the value for T00_COM_AUTH.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_COM_AUTH.MODIFYDATE
     *
     * @return the value of T00_COM_AUTH.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_COM_AUTH.MODIFYDATE
     *
     * @param modifydate the value for T00_COM_AUTH.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModifydate(String modifydate) {
        this.modifydate = modifydate == null ? null : modifydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_COM_AUTH.MODIFIER
     *
     * @return the value of T00_COM_AUTH.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_COM_AUTH.MODIFIER
     *
     * @param modifier the value for T00_COM_AUTH.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}