package com.demo.aml.pojo;

public class T00ComAuthKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_COM_AUTH.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_COM_AUTH.ROLEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String rolekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_COM_AUTH.GROUPKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String groupkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_COM_AUTH.USERNAME
     *
     * @return the value of T00_COM_AUTH.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_COM_AUTH.USERNAME
     *
     * @param username the value for T00_COM_AUTH.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_COM_AUTH.ROLEKEY
     *
     * @return the value of T00_COM_AUTH.ROLEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getRolekey() {
        return rolekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_COM_AUTH.ROLEKEY
     *
     * @param rolekey the value for T00_COM_AUTH.ROLEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setRolekey(String rolekey) {
        this.rolekey = rolekey == null ? null : rolekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_COM_AUTH.GROUPKEY
     *
     * @return the value of T00_COM_AUTH.GROUPKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getGroupkey() {
        return groupkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_COM_AUTH.GROUPKEY
     *
     * @param groupkey the value for T00_COM_AUTH.GROUPKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setGroupkey(String groupkey) {
        this.groupkey = groupkey == null ? null : groupkey.trim();
    }
}