package com.demo.aml.pojo;

import java.util.ArrayList;
import java.util.List;

public class T00DictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public T00DictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDisctypeIsNull() {
            addCriterion("DISCTYPE is null");
            return (Criteria) this;
        }

        public Criteria andDisctypeIsNotNull() {
            addCriterion("DISCTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDisctypeEqualTo(String value) {
            addCriterion("DISCTYPE =", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeNotEqualTo(String value) {
            addCriterion("DISCTYPE <>", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeGreaterThan(String value) {
            addCriterion("DISCTYPE >", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeGreaterThanOrEqualTo(String value) {
            addCriterion("DISCTYPE >=", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeLessThan(String value) {
            addCriterion("DISCTYPE <", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeLessThanOrEqualTo(String value) {
            addCriterion("DISCTYPE <=", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeLike(String value) {
            addCriterion("DISCTYPE like", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeNotLike(String value) {
            addCriterion("DISCTYPE not like", value, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeIn(List<String> values) {
            addCriterion("DISCTYPE in", values, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeNotIn(List<String> values) {
            addCriterion("DISCTYPE not in", values, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeBetween(String value1, String value2) {
            addCriterion("DISCTYPE between", value1, value2, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypeNotBetween(String value1, String value2) {
            addCriterion("DISCTYPE not between", value1, value2, "disctype");
            return (Criteria) this;
        }

        public Criteria andDisctypenameIsNull() {
            addCriterion("DISCTYPENAME is null");
            return (Criteria) this;
        }

        public Criteria andDisctypenameIsNotNull() {
            addCriterion("DISCTYPENAME is not null");
            return (Criteria) this;
        }

        public Criteria andDisctypenameEqualTo(String value) {
            addCriterion("DISCTYPENAME =", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameNotEqualTo(String value) {
            addCriterion("DISCTYPENAME <>", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameGreaterThan(String value) {
            addCriterion("DISCTYPENAME >", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameGreaterThanOrEqualTo(String value) {
            addCriterion("DISCTYPENAME >=", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameLessThan(String value) {
            addCriterion("DISCTYPENAME <", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameLessThanOrEqualTo(String value) {
            addCriterion("DISCTYPENAME <=", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameLike(String value) {
            addCriterion("DISCTYPENAME like", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameNotLike(String value) {
            addCriterion("DISCTYPENAME not like", value, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameIn(List<String> values) {
            addCriterion("DISCTYPENAME in", values, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameNotIn(List<String> values) {
            addCriterion("DISCTYPENAME not in", values, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameBetween(String value1, String value2) {
            addCriterion("DISCTYPENAME between", value1, value2, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisctypenameNotBetween(String value1, String value2) {
            addCriterion("DISCTYPENAME not between", value1, value2, "disctypename");
            return (Criteria) this;
        }

        public Criteria andDisckeyIsNull() {
            addCriterion("DISCKEY is null");
            return (Criteria) this;
        }

        public Criteria andDisckeyIsNotNull() {
            addCriterion("DISCKEY is not null");
            return (Criteria) this;
        }

        public Criteria andDisckeyEqualTo(String value) {
            addCriterion("DISCKEY =", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyNotEqualTo(String value) {
            addCriterion("DISCKEY <>", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyGreaterThan(String value) {
            addCriterion("DISCKEY >", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyGreaterThanOrEqualTo(String value) {
            addCriterion("DISCKEY >=", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyLessThan(String value) {
            addCriterion("DISCKEY <", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyLessThanOrEqualTo(String value) {
            addCriterion("DISCKEY <=", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyLike(String value) {
            addCriterion("DISCKEY like", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyNotLike(String value) {
            addCriterion("DISCKEY not like", value, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyIn(List<String> values) {
            addCriterion("DISCKEY in", values, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyNotIn(List<String> values) {
            addCriterion("DISCKEY not in", values, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyBetween(String value1, String value2) {
            addCriterion("DISCKEY between", value1, value2, "disckey");
            return (Criteria) this;
        }

        public Criteria andDisckeyNotBetween(String value1, String value2) {
            addCriterion("DISCKEY not between", value1, value2, "disckey");
            return (Criteria) this;
        }

        public Criteria andDiscnameIsNull() {
            addCriterion("DISCNAME is null");
            return (Criteria) this;
        }

        public Criteria andDiscnameIsNotNull() {
            addCriterion("DISCNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDiscnameEqualTo(String value) {
            addCriterion("DISCNAME =", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameNotEqualTo(String value) {
            addCriterion("DISCNAME <>", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameGreaterThan(String value) {
            addCriterion("DISCNAME >", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameGreaterThanOrEqualTo(String value) {
            addCriterion("DISCNAME >=", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameLessThan(String value) {
            addCriterion("DISCNAME <", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameLessThanOrEqualTo(String value) {
            addCriterion("DISCNAME <=", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameLike(String value) {
            addCriterion("DISCNAME like", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameNotLike(String value) {
            addCriterion("DISCNAME not like", value, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameIn(List<String> values) {
            addCriterion("DISCNAME in", values, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameNotIn(List<String> values) {
            addCriterion("DISCNAME not in", values, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameBetween(String value1, String value2) {
            addCriterion("DISCNAME between", value1, value2, "discname");
            return (Criteria) this;
        }

        public Criteria andDiscnameNotBetween(String value1, String value2) {
            addCriterion("DISCNAME not between", value1, value2, "discname");
            return (Criteria) this;
        }

        public Criteria andDesIsNull() {
            addCriterion("DES is null");
            return (Criteria) this;
        }

        public Criteria andDesIsNotNull() {
            addCriterion("DES is not null");
            return (Criteria) this;
        }

        public Criteria andDesEqualTo(String value) {
            addCriterion("DES =", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotEqualTo(String value) {
            addCriterion("DES <>", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThan(String value) {
            addCriterion("DES >", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThanOrEqualTo(String value) {
            addCriterion("DES >=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThan(String value) {
            addCriterion("DES <", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThanOrEqualTo(String value) {
            addCriterion("DES <=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLike(String value) {
            addCriterion("DES like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotLike(String value) {
            addCriterion("DES not like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesIn(List<String> values) {
            addCriterion("DES in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotIn(List<String> values) {
            addCriterion("DES not in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesBetween(String value1, String value2) {
            addCriterion("DES between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotBetween(String value1, String value2) {
            addCriterion("DES not between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(String value) {
            addCriterion("FLAG =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(String value) {
            addCriterion("FLAG <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(String value) {
            addCriterion("FLAG >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(String value) {
            addCriterion("FLAG >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(String value) {
            addCriterion("FLAG <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(String value) {
            addCriterion("FLAG <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLike(String value) {
            addCriterion("FLAG like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotLike(String value) {
            addCriterion("FLAG not like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<String> values) {
            addCriterion("FLAG in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<String> values) {
            addCriterion("FLAG not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(String value1, String value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(String value1, String value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andDispseqIsNull() {
            addCriterion("DISPSEQ is null");
            return (Criteria) this;
        }

        public Criteria andDispseqIsNotNull() {
            addCriterion("DISPSEQ is not null");
            return (Criteria) this;
        }

        public Criteria andDispseqEqualTo(Long value) {
            addCriterion("DISPSEQ =", value, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqNotEqualTo(Long value) {
            addCriterion("DISPSEQ <>", value, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqGreaterThan(Long value) {
            addCriterion("DISPSEQ >", value, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqGreaterThanOrEqualTo(Long value) {
            addCriterion("DISPSEQ >=", value, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqLessThan(Long value) {
            addCriterion("DISPSEQ <", value, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqLessThanOrEqualTo(Long value) {
            addCriterion("DISPSEQ <=", value, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqIn(List<Long> values) {
            addCriterion("DISPSEQ in", values, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqNotIn(List<Long> values) {
            addCriterion("DISPSEQ not in", values, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqBetween(Long value1, Long value2) {
            addCriterion("DISPSEQ between", value1, value2, "dispseq");
            return (Criteria) this;
        }

        public Criteria andDispseqNotBetween(Long value1, Long value2) {
            addCriterion("DISPSEQ not between", value1, value2, "dispseq");
            return (Criteria) this;
        }

        public Criteria andIsbuildinIsNull() {
            addCriterion("ISBUILDIN is null");
            return (Criteria) this;
        }

        public Criteria andIsbuildinIsNotNull() {
            addCriterion("ISBUILDIN is not null");
            return (Criteria) this;
        }

        public Criteria andIsbuildinEqualTo(String value) {
            addCriterion("ISBUILDIN =", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinNotEqualTo(String value) {
            addCriterion("ISBUILDIN <>", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinGreaterThan(String value) {
            addCriterion("ISBUILDIN >", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinGreaterThanOrEqualTo(String value) {
            addCriterion("ISBUILDIN >=", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinLessThan(String value) {
            addCriterion("ISBUILDIN <", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinLessThanOrEqualTo(String value) {
            addCriterion("ISBUILDIN <=", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinLike(String value) {
            addCriterion("ISBUILDIN like", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinNotLike(String value) {
            addCriterion("ISBUILDIN not like", value, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinIn(List<String> values) {
            addCriterion("ISBUILDIN in", values, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinNotIn(List<String> values) {
            addCriterion("ISBUILDIN not in", values, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinBetween(String value1, String value2) {
            addCriterion("ISBUILDIN between", value1, value2, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andIsbuildinNotBetween(String value1, String value2) {
            addCriterion("ISBUILDIN not between", value1, value2, "isbuildin");
            return (Criteria) this;
        }

        public Criteria andApplytypeIsNull() {
            addCriterion("APPLYTYPE is null");
            return (Criteria) this;
        }

        public Criteria andApplytypeIsNotNull() {
            addCriterion("APPLYTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andApplytypeEqualTo(String value) {
            addCriterion("APPLYTYPE =", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeNotEqualTo(String value) {
            addCriterion("APPLYTYPE <>", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeGreaterThan(String value) {
            addCriterion("APPLYTYPE >", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeGreaterThanOrEqualTo(String value) {
            addCriterion("APPLYTYPE >=", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeLessThan(String value) {
            addCriterion("APPLYTYPE <", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeLessThanOrEqualTo(String value) {
            addCriterion("APPLYTYPE <=", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeLike(String value) {
            addCriterion("APPLYTYPE like", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeNotLike(String value) {
            addCriterion("APPLYTYPE not like", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeIn(List<String> values) {
            addCriterion("APPLYTYPE in", values, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeNotIn(List<String> values) {
            addCriterion("APPLYTYPE not in", values, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeBetween(String value1, String value2) {
            addCriterion("APPLYTYPE between", value1, value2, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeNotBetween(String value1, String value2) {
            addCriterion("APPLYTYPE not between", value1, value2, "applytype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_DICT
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_DICT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}