package com.demo.aml.pojo;

import java.util.Date;

public class T00Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modulekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.SYSTEMKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String systemkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.MODULENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modulename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.URL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.UPMODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String upmodulekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.DISPLAYSEQ
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private Long displayseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_MODULE.IMGURL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.MODULEKEY
     *
     * @return the value of T00_MODULE.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModulekey() {
        return modulekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.MODULEKEY
     *
     * @param modulekey the value for T00_MODULE.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModulekey(String modulekey) {
        this.modulekey = modulekey == null ? null : modulekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.SYSTEMKEY
     *
     * @return the value of T00_MODULE.SYSTEMKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getSystemkey() {
        return systemkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.SYSTEMKEY
     *
     * @param systemkey the value for T00_MODULE.SYSTEMKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setSystemkey(String systemkey) {
        this.systemkey = systemkey == null ? null : systemkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.MODULENAME
     *
     * @return the value of T00_MODULE.MODULENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.MODULENAME
     *
     * @param modulename the value for T00_MODULE.MODULENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.URL
     *
     * @return the value of T00_MODULE.URL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.URL
     *
     * @param url the value for T00_MODULE.URL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.UPMODULEKEY
     *
     * @return the value of T00_MODULE.UPMODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getUpmodulekey() {
        return upmodulekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.UPMODULEKEY
     *
     * @param upmodulekey the value for T00_MODULE.UPMODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setUpmodulekey(String upmodulekey) {
        this.upmodulekey = upmodulekey == null ? null : upmodulekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.DISPLAYSEQ
     *
     * @return the value of T00_MODULE.DISPLAYSEQ
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Long getDisplayseq() {
        return displayseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.DISPLAYSEQ
     *
     * @param displayseq the value for T00_MODULE.DISPLAYSEQ
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setDisplayseq(Long displayseq) {
        this.displayseq = displayseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.CREATEDATE
     *
     * @return the value of T00_MODULE.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.CREATEDATE
     *
     * @param createdate the value for T00_MODULE.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.CREATOR
     *
     * @return the value of T00_MODULE.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.CREATOR
     *
     * @param creator the value for T00_MODULE.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.MODIFYDATE
     *
     * @return the value of T00_MODULE.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.MODIFYDATE
     *
     * @param modifydate the value for T00_MODULE.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.MODIFIER
     *
     * @return the value of T00_MODULE.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.MODIFIER
     *
     * @param modifier the value for T00_MODULE.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_MODULE.IMGURL
     *
     * @return the value of T00_MODULE.IMGURL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_MODULE.IMGURL
     *
     * @param imgurl the value for T00_MODULE.IMGURL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}