package com.demo.aml.pojo;

public class T00Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.NOTEICE_NO
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String noteiceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.NOTICE_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String noticeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.NOTICE_GORY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String noticeGory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.TITLE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.CONTENT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.FILENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.FILEPATH
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.INFACTDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String infactdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.CREATEORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String createorgan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_NOTICE.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.NOTEICE_NO
     *
     * @return the value of T00_NOTICE.NOTEICE_NO
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getNoteiceNo() {
        return noteiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.NOTEICE_NO
     *
     * @param noteiceNo the value for T00_NOTICE.NOTEICE_NO
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setNoteiceNo(String noteiceNo) {
        this.noteiceNo = noteiceNo == null ? null : noteiceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.NOTICE_TYPE
     *
     * @return the value of T00_NOTICE.NOTICE_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.NOTICE_TYPE
     *
     * @param noticeType the value for T00_NOTICE.NOTICE_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setNoticeType(String noticeType) {
        this.noticeType = noticeType == null ? null : noticeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.NOTICE_GORY
     *
     * @return the value of T00_NOTICE.NOTICE_GORY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getNoticeGory() {
        return noticeGory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.NOTICE_GORY
     *
     * @param noticeGory the value for T00_NOTICE.NOTICE_GORY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setNoticeGory(String noticeGory) {
        this.noticeGory = noticeGory == null ? null : noticeGory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.TITLE
     *
     * @return the value of T00_NOTICE.TITLE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.TITLE
     *
     * @param title the value for T00_NOTICE.TITLE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.CONTENT
     *
     * @return the value of T00_NOTICE.CONTENT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.CONTENT
     *
     * @param content the value for T00_NOTICE.CONTENT
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.FILENAME
     *
     * @return the value of T00_NOTICE.FILENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.FILENAME
     *
     * @param filename the value for T00_NOTICE.FILENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.FILEPATH
     *
     * @return the value of T00_NOTICE.FILEPATH
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.FILEPATH
     *
     * @param filepath the value for T00_NOTICE.FILEPATH
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.INFACTDATE
     *
     * @return the value of T00_NOTICE.INFACTDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getInfactdate() {
        return infactdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.INFACTDATE
     *
     * @param infactdate the value for T00_NOTICE.INFACTDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setInfactdate(String infactdate) {
        this.infactdate = infactdate == null ? null : infactdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.FLAG
     *
     * @return the value of T00_NOTICE.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.FLAG
     *
     * @param flag the value for T00_NOTICE.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.CREATEDATE
     *
     * @return the value of T00_NOTICE.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.CREATEDATE
     *
     * @param createdate the value for T00_NOTICE.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.CREATEORGAN
     *
     * @return the value of T00_NOTICE.CREATEORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreateorgan() {
        return createorgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.CREATEORGAN
     *
     * @param createorgan the value for T00_NOTICE.CREATEORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreateorgan(String createorgan) {
        this.createorgan = createorgan == null ? null : createorgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_NOTICE.CREATOR
     *
     * @return the value of T00_NOTICE.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_NOTICE.CREATOR
     *
     * @param creator the value for T00_NOTICE.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}