package com.demo.aml.pojo;

import java.util.Date;

public class T00OperateLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.LOG_KEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String logKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.REALNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.SYSTEMKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String systemkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modulekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.MODULENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modulename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.MODULE_KEY_SUB1
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String moduleKeySub1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.MODULE_KEY_SUB2
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String moduleKeySub2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.OPERATE_OBJ1_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String operateObj1Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.OPERATE_OBJ2_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String operateObj2Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.OPERATE_OBJ1
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String operateObj1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.OPERATE_OBJ2
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String operateObj2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.OPERATE_DESC
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String operateDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.OPERATE_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_OPERATE_LOG.IS_SUCC
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String isSucc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.LOG_KEY
     *
     * @return the value of T00_OPERATE_LOG.LOG_KEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getLogKey() {
        return logKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.LOG_KEY
     *
     * @param logKey the value for T00_OPERATE_LOG.LOG_KEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setLogKey(String logKey) {
        this.logKey = logKey == null ? null : logKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.CREATEDATE
     *
     * @return the value of T00_OPERATE_LOG.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.CREATEDATE
     *
     * @param createdate the value for T00_OPERATE_LOG.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.USERNAME
     *
     * @return the value of T00_OPERATE_LOG.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.USERNAME
     *
     * @param username the value for T00_OPERATE_LOG.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.REALNAME
     *
     * @return the value of T00_OPERATE_LOG.REALNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.REALNAME
     *
     * @param realname the value for T00_OPERATE_LOG.REALNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.SYSTEMKEY
     *
     * @return the value of T00_OPERATE_LOG.SYSTEMKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getSystemkey() {
        return systemkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.SYSTEMKEY
     *
     * @param systemkey the value for T00_OPERATE_LOG.SYSTEMKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setSystemkey(String systemkey) {
        this.systemkey = systemkey == null ? null : systemkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.MODULEKEY
     *
     * @return the value of T00_OPERATE_LOG.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModulekey() {
        return modulekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.MODULEKEY
     *
     * @param modulekey the value for T00_OPERATE_LOG.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModulekey(String modulekey) {
        this.modulekey = modulekey == null ? null : modulekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.MODULENAME
     *
     * @return the value of T00_OPERATE_LOG.MODULENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.MODULENAME
     *
     * @param modulename the value for T00_OPERATE_LOG.MODULENAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.MODULE_KEY_SUB1
     *
     * @return the value of T00_OPERATE_LOG.MODULE_KEY_SUB1
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModuleKeySub1() {
        return moduleKeySub1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.MODULE_KEY_SUB1
     *
     * @param moduleKeySub1 the value for T00_OPERATE_LOG.MODULE_KEY_SUB1
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModuleKeySub1(String moduleKeySub1) {
        this.moduleKeySub1 = moduleKeySub1 == null ? null : moduleKeySub1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.MODULE_KEY_SUB2
     *
     * @return the value of T00_OPERATE_LOG.MODULE_KEY_SUB2
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModuleKeySub2() {
        return moduleKeySub2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.MODULE_KEY_SUB2
     *
     * @param moduleKeySub2 the value for T00_OPERATE_LOG.MODULE_KEY_SUB2
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModuleKeySub2(String moduleKeySub2) {
        this.moduleKeySub2 = moduleKeySub2 == null ? null : moduleKeySub2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.OPERATE_OBJ1_TYPE
     *
     * @return the value of T00_OPERATE_LOG.OPERATE_OBJ1_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOperateObj1Type() {
        return operateObj1Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.OPERATE_OBJ1_TYPE
     *
     * @param operateObj1Type the value for T00_OPERATE_LOG.OPERATE_OBJ1_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOperateObj1Type(String operateObj1Type) {
        this.operateObj1Type = operateObj1Type == null ? null : operateObj1Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.OPERATE_OBJ2_TYPE
     *
     * @return the value of T00_OPERATE_LOG.OPERATE_OBJ2_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOperateObj2Type() {
        return operateObj2Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.OPERATE_OBJ2_TYPE
     *
     * @param operateObj2Type the value for T00_OPERATE_LOG.OPERATE_OBJ2_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOperateObj2Type(String operateObj2Type) {
        this.operateObj2Type = operateObj2Type == null ? null : operateObj2Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.OPERATE_OBJ1
     *
     * @return the value of T00_OPERATE_LOG.OPERATE_OBJ1
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOperateObj1() {
        return operateObj1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.OPERATE_OBJ1
     *
     * @param operateObj1 the value for T00_OPERATE_LOG.OPERATE_OBJ1
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOperateObj1(String operateObj1) {
        this.operateObj1 = operateObj1 == null ? null : operateObj1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.OPERATE_OBJ2
     *
     * @return the value of T00_OPERATE_LOG.OPERATE_OBJ2
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOperateObj2() {
        return operateObj2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.OPERATE_OBJ2
     *
     * @param operateObj2 the value for T00_OPERATE_LOG.OPERATE_OBJ2
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOperateObj2(String operateObj2) {
        this.operateObj2 = operateObj2 == null ? null : operateObj2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.OPERATE_DESC
     *
     * @return the value of T00_OPERATE_LOG.OPERATE_DESC
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOperateDesc() {
        return operateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.OPERATE_DESC
     *
     * @param operateDesc the value for T00_OPERATE_LOG.OPERATE_DESC
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOperateDesc(String operateDesc) {
        this.operateDesc = operateDesc == null ? null : operateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.OPERATE_TYPE
     *
     * @return the value of T00_OPERATE_LOG.OPERATE_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.OPERATE_TYPE
     *
     * @param operateType the value for T00_OPERATE_LOG.OPERATE_TYPE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_OPERATE_LOG.IS_SUCC
     *
     * @return the value of T00_OPERATE_LOG.IS_SUCC
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getIsSucc() {
        return isSucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_OPERATE_LOG.IS_SUCC
     *
     * @param isSucc the value for T00_OPERATE_LOG.IS_SUCC
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setIsSucc(String isSucc) {
        this.isSucc = isSucc == null ? null : isSucc.trim();
    }
}