package com.demo.aml.pojo;

import java.util.ArrayList;
import java.util.List;

public class T00OrganExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public T00OrganExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrgankeyIsNull() {
            addCriterion("ORGANKEY is null");
            return (Criteria) this;
        }

        public Criteria andOrgankeyIsNotNull() {
            addCriterion("ORGANKEY is not null");
            return (Criteria) this;
        }

        public Criteria andOrgankeyEqualTo(String value) {
            addCriterion("ORGANKEY =", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotEqualTo(String value) {
            addCriterion("ORGANKEY <>", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyGreaterThan(String value) {
            addCriterion("ORGANKEY >", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANKEY >=", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyLessThan(String value) {
            addCriterion("ORGANKEY <", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyLessThanOrEqualTo(String value) {
            addCriterion("ORGANKEY <=", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyLike(String value) {
            addCriterion("ORGANKEY like", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotLike(String value) {
            addCriterion("ORGANKEY not like", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyIn(List<String> values) {
            addCriterion("ORGANKEY in", values, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotIn(List<String> values) {
            addCriterion("ORGANKEY not in", values, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyBetween(String value1, String value2) {
            addCriterion("ORGANKEY between", value1, value2, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotBetween(String value1, String value2) {
            addCriterion("ORGANKEY not between", value1, value2, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgannoIsNull() {
            addCriterion("ORGANNO is null");
            return (Criteria) this;
        }

        public Criteria andOrgannoIsNotNull() {
            addCriterion("ORGANNO is not null");
            return (Criteria) this;
        }

        public Criteria andOrgannoEqualTo(String value) {
            addCriterion("ORGANNO =", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoNotEqualTo(String value) {
            addCriterion("ORGANNO <>", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoGreaterThan(String value) {
            addCriterion("ORGANNO >", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANNO >=", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoLessThan(String value) {
            addCriterion("ORGANNO <", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoLessThanOrEqualTo(String value) {
            addCriterion("ORGANNO <=", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoLike(String value) {
            addCriterion("ORGANNO like", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoNotLike(String value) {
            addCriterion("ORGANNO not like", value, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoIn(List<String> values) {
            addCriterion("ORGANNO in", values, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoNotIn(List<String> values) {
            addCriterion("ORGANNO not in", values, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoBetween(String value1, String value2) {
            addCriterion("ORGANNO between", value1, value2, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannoNotBetween(String value1, String value2) {
            addCriterion("ORGANNO not between", value1, value2, "organno");
            return (Criteria) this;
        }

        public Criteria andOrgannameIsNull() {
            addCriterion("ORGANNAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgannameIsNotNull() {
            addCriterion("ORGANNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgannameEqualTo(String value) {
            addCriterion("ORGANNAME =", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameNotEqualTo(String value) {
            addCriterion("ORGANNAME <>", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameGreaterThan(String value) {
            addCriterion("ORGANNAME >", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANNAME >=", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameLessThan(String value) {
            addCriterion("ORGANNAME <", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameLessThanOrEqualTo(String value) {
            addCriterion("ORGANNAME <=", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameLike(String value) {
            addCriterion("ORGANNAME like", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameNotLike(String value) {
            addCriterion("ORGANNAME not like", value, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameIn(List<String> values) {
            addCriterion("ORGANNAME in", values, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameNotIn(List<String> values) {
            addCriterion("ORGANNAME not in", values, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameBetween(String value1, String value2) {
            addCriterion("ORGANNAME between", value1, value2, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgannameNotBetween(String value1, String value2) {
            addCriterion("ORGANNAME not between", value1, value2, "organname");
            return (Criteria) this;
        }

        public Criteria andOrgansfIsNull() {
            addCriterion("ORGANSF is null");
            return (Criteria) this;
        }

        public Criteria andOrgansfIsNotNull() {
            addCriterion("ORGANSF is not null");
            return (Criteria) this;
        }

        public Criteria andOrgansfEqualTo(String value) {
            addCriterion("ORGANSF =", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfNotEqualTo(String value) {
            addCriterion("ORGANSF <>", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfGreaterThan(String value) {
            addCriterion("ORGANSF >", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANSF >=", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfLessThan(String value) {
            addCriterion("ORGANSF <", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfLessThanOrEqualTo(String value) {
            addCriterion("ORGANSF <=", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfLike(String value) {
            addCriterion("ORGANSF like", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfNotLike(String value) {
            addCriterion("ORGANSF not like", value, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfIn(List<String> values) {
            addCriterion("ORGANSF in", values, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfNotIn(List<String> values) {
            addCriterion("ORGANSF not in", values, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfBetween(String value1, String value2) {
            addCriterion("ORGANSF between", value1, value2, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrgansfNotBetween(String value1, String value2) {
            addCriterion("ORGANSF not between", value1, value2, "organsf");
            return (Criteria) this;
        }

        public Criteria andOrganlevelIsNull() {
            addCriterion("ORGANLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andOrganlevelIsNotNull() {
            addCriterion("ORGANLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andOrganlevelEqualTo(String value) {
            addCriterion("ORGANLEVEL =", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotEqualTo(String value) {
            addCriterion("ORGANLEVEL <>", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelGreaterThan(String value) {
            addCriterion("ORGANLEVEL >", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANLEVEL >=", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelLessThan(String value) {
            addCriterion("ORGANLEVEL <", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelLessThanOrEqualTo(String value) {
            addCriterion("ORGANLEVEL <=", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelLike(String value) {
            addCriterion("ORGANLEVEL like", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotLike(String value) {
            addCriterion("ORGANLEVEL not like", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelIn(List<String> values) {
            addCriterion("ORGANLEVEL in", values, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotIn(List<String> values) {
            addCriterion("ORGANLEVEL not in", values, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelBetween(String value1, String value2) {
            addCriterion("ORGANLEVEL between", value1, value2, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotBetween(String value1, String value2) {
            addCriterion("ORGANLEVEL not between", value1, value2, "organlevel");
            return (Criteria) this;
        }

        public Criteria andUporgankeyIsNull() {
            addCriterion("UPORGANKEY is null");
            return (Criteria) this;
        }

        public Criteria andUporgankeyIsNotNull() {
            addCriterion("UPORGANKEY is not null");
            return (Criteria) this;
        }

        public Criteria andUporgankeyEqualTo(String value) {
            addCriterion("UPORGANKEY =", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyNotEqualTo(String value) {
            addCriterion("UPORGANKEY <>", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyGreaterThan(String value) {
            addCriterion("UPORGANKEY >", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyGreaterThanOrEqualTo(String value) {
            addCriterion("UPORGANKEY >=", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyLessThan(String value) {
            addCriterion("UPORGANKEY <", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyLessThanOrEqualTo(String value) {
            addCriterion("UPORGANKEY <=", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyLike(String value) {
            addCriterion("UPORGANKEY like", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyNotLike(String value) {
            addCriterion("UPORGANKEY not like", value, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyIn(List<String> values) {
            addCriterion("UPORGANKEY in", values, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyNotIn(List<String> values) {
            addCriterion("UPORGANKEY not in", values, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyBetween(String value1, String value2) {
            addCriterion("UPORGANKEY between", value1, value2, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andUporgankeyNotBetween(String value1, String value2) {
            addCriterion("UPORGANKEY not between", value1, value2, "uporgankey");
            return (Criteria) this;
        }

        public Criteria andOrganaddressIsNull() {
            addCriterion("ORGANADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andOrganaddressIsNotNull() {
            addCriterion("ORGANADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andOrganaddressEqualTo(String value) {
            addCriterion("ORGANADDRESS =", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressNotEqualTo(String value) {
            addCriterion("ORGANADDRESS <>", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressGreaterThan(String value) {
            addCriterion("ORGANADDRESS >", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANADDRESS >=", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressLessThan(String value) {
            addCriterion("ORGANADDRESS <", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressLessThanOrEqualTo(String value) {
            addCriterion("ORGANADDRESS <=", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressLike(String value) {
            addCriterion("ORGANADDRESS like", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressNotLike(String value) {
            addCriterion("ORGANADDRESS not like", value, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressIn(List<String> values) {
            addCriterion("ORGANADDRESS in", values, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressNotIn(List<String> values) {
            addCriterion("ORGANADDRESS not in", values, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressBetween(String value1, String value2) {
            addCriterion("ORGANADDRESS between", value1, value2, "organaddress");
            return (Criteria) this;
        }

        public Criteria andOrganaddressNotBetween(String value1, String value2) {
            addCriterion("ORGANADDRESS not between", value1, value2, "organaddress");
            return (Criteria) this;
        }

        public Criteria andPostalcodeIsNull() {
            addCriterion("POSTALCODE is null");
            return (Criteria) this;
        }

        public Criteria andPostalcodeIsNotNull() {
            addCriterion("POSTALCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPostalcodeEqualTo(String value) {
            addCriterion("POSTALCODE =", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeNotEqualTo(String value) {
            addCriterion("POSTALCODE <>", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeGreaterThan(String value) {
            addCriterion("POSTALCODE >", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeGreaterThanOrEqualTo(String value) {
            addCriterion("POSTALCODE >=", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeLessThan(String value) {
            addCriterion("POSTALCODE <", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeLessThanOrEqualTo(String value) {
            addCriterion("POSTALCODE <=", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeLike(String value) {
            addCriterion("POSTALCODE like", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeNotLike(String value) {
            addCriterion("POSTALCODE not like", value, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeIn(List<String> values) {
            addCriterion("POSTALCODE in", values, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeNotIn(List<String> values) {
            addCriterion("POSTALCODE not in", values, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeBetween(String value1, String value2) {
            addCriterion("POSTALCODE between", value1, value2, "postalcode");
            return (Criteria) this;
        }

        public Criteria andPostalcodeNotBetween(String value1, String value2) {
            addCriterion("POSTALCODE not between", value1, value2, "postalcode");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("TELEPHONE is null");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("TELEPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andTelephoneEqualTo(String value) {
            addCriterion("TELEPHONE =", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotEqualTo(String value) {
            addCriterion("TELEPHONE <>", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThan(String value) {
            addCriterion("TELEPHONE >", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("TELEPHONE >=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThan(String value) {
            addCriterion("TELEPHONE <", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(String value) {
            addCriterion("TELEPHONE <=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLike(String value) {
            addCriterion("TELEPHONE like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotLike(String value) {
            addCriterion("TELEPHONE not like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneIn(List<String> values) {
            addCriterion("TELEPHONE in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotIn(List<String> values) {
            addCriterion("TELEPHONE not in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneBetween(String value1, String value2) {
            addCriterion("TELEPHONE between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotBetween(String value1, String value2) {
            addCriterion("TELEPHONE not between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerIsNull() {
            addCriterion("ORGANMANAGER is null");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerIsNotNull() {
            addCriterion("ORGANMANAGER is not null");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerEqualTo(String value) {
            addCriterion("ORGANMANAGER =", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerNotEqualTo(String value) {
            addCriterion("ORGANMANAGER <>", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerGreaterThan(String value) {
            addCriterion("ORGANMANAGER >", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANMANAGER >=", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerLessThan(String value) {
            addCriterion("ORGANMANAGER <", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerLessThanOrEqualTo(String value) {
            addCriterion("ORGANMANAGER <=", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerLike(String value) {
            addCriterion("ORGANMANAGER like", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerNotLike(String value) {
            addCriterion("ORGANMANAGER not like", value, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerIn(List<String> values) {
            addCriterion("ORGANMANAGER in", values, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerNotIn(List<String> values) {
            addCriterion("ORGANMANAGER not in", values, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerBetween(String value1, String value2) {
            addCriterion("ORGANMANAGER between", value1, value2, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganmanagerNotBetween(String value1, String value2) {
            addCriterion("ORGANMANAGER not between", value1, value2, "organmanager");
            return (Criteria) this;
        }

        public Criteria andOrganpamountIsNull() {
            addCriterion("ORGANPAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andOrganpamountIsNotNull() {
            addCriterion("ORGANPAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andOrganpamountEqualTo(Integer value) {
            addCriterion("ORGANPAMOUNT =", value, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountNotEqualTo(Integer value) {
            addCriterion("ORGANPAMOUNT <>", value, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountGreaterThan(Integer value) {
            addCriterion("ORGANPAMOUNT >", value, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORGANPAMOUNT >=", value, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountLessThan(Integer value) {
            addCriterion("ORGANPAMOUNT <", value, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountLessThanOrEqualTo(Integer value) {
            addCriterion("ORGANPAMOUNT <=", value, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountIn(List<Integer> values) {
            addCriterion("ORGANPAMOUNT in", values, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountNotIn(List<Integer> values) {
            addCriterion("ORGANPAMOUNT not in", values, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountBetween(Integer value1, Integer value2) {
            addCriterion("ORGANPAMOUNT between", value1, value2, "organpamount");
            return (Criteria) this;
        }

        public Criteria andOrganpamountNotBetween(Integer value1, Integer value2) {
            addCriterion("ORGANPAMOUNT not between", value1, value2, "organpamount");
            return (Criteria) this;
        }

        public Criteria andLinkmanIsNull() {
            addCriterion("LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanIsNotNull() {
            addCriterion("LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanEqualTo(String value) {
            addCriterion("LINKMAN =", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotEqualTo(String value) {
            addCriterion("LINKMAN <>", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanGreaterThan(String value) {
            addCriterion("LINKMAN >", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("LINKMAN >=", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLessThan(String value) {
            addCriterion("LINKMAN <", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLessThanOrEqualTo(String value) {
            addCriterion("LINKMAN <=", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLike(String value) {
            addCriterion("LINKMAN like", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotLike(String value) {
            addCriterion("LINKMAN not like", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanIn(List<String> values) {
            addCriterion("LINKMAN in", values, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotIn(List<String> values) {
            addCriterion("LINKMAN not in", values, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanBetween(String value1, String value2) {
            addCriterion("LINKMAN between", value1, value2, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotBetween(String value1, String value2) {
            addCriterion("LINKMAN not between", value1, value2, "linkman");
            return (Criteria) this;
        }

        public Criteria andBuilddateIsNull() {
            addCriterion("BUILDDATE is null");
            return (Criteria) this;
        }

        public Criteria andBuilddateIsNotNull() {
            addCriterion("BUILDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBuilddateEqualTo(String value) {
            addCriterion("BUILDDATE =", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateNotEqualTo(String value) {
            addCriterion("BUILDDATE <>", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateGreaterThan(String value) {
            addCriterion("BUILDDATE >", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateGreaterThanOrEqualTo(String value) {
            addCriterion("BUILDDATE >=", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateLessThan(String value) {
            addCriterion("BUILDDATE <", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateLessThanOrEqualTo(String value) {
            addCriterion("BUILDDATE <=", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateLike(String value) {
            addCriterion("BUILDDATE like", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateNotLike(String value) {
            addCriterion("BUILDDATE not like", value, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateIn(List<String> values) {
            addCriterion("BUILDDATE in", values, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateNotIn(List<String> values) {
            addCriterion("BUILDDATE not in", values, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateBetween(String value1, String value2) {
            addCriterion("BUILDDATE between", value1, value2, "builddate");
            return (Criteria) this;
        }

        public Criteria andBuilddateNotBetween(String value1, String value2) {
            addCriterion("BUILDDATE not between", value1, value2, "builddate");
            return (Criteria) this;
        }

        public Criteria andOrgandesIsNull() {
            addCriterion("ORGANDES is null");
            return (Criteria) this;
        }

        public Criteria andOrgandesIsNotNull() {
            addCriterion("ORGANDES is not null");
            return (Criteria) this;
        }

        public Criteria andOrgandesEqualTo(String value) {
            addCriterion("ORGANDES =", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesNotEqualTo(String value) {
            addCriterion("ORGANDES <>", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesGreaterThan(String value) {
            addCriterion("ORGANDES >", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANDES >=", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesLessThan(String value) {
            addCriterion("ORGANDES <", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesLessThanOrEqualTo(String value) {
            addCriterion("ORGANDES <=", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesLike(String value) {
            addCriterion("ORGANDES like", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesNotLike(String value) {
            addCriterion("ORGANDES not like", value, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesIn(List<String> values) {
            addCriterion("ORGANDES in", values, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesNotIn(List<String> values) {
            addCriterion("ORGANDES not in", values, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesBetween(String value1, String value2) {
            addCriterion("ORGANDES between", value1, value2, "organdes");
            return (Criteria) this;
        }

        public Criteria andOrgandesNotBetween(String value1, String value2) {
            addCriterion("ORGANDES not between", value1, value2, "organdes");
            return (Criteria) this;
        }

        public Criteria andValidatedateIsNull() {
            addCriterion("VALIDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andValidatedateIsNotNull() {
            addCriterion("VALIDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andValidatedateEqualTo(String value) {
            addCriterion("VALIDATEDATE =", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateNotEqualTo(String value) {
            addCriterion("VALIDATEDATE <>", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateGreaterThan(String value) {
            addCriterion("VALIDATEDATE >", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateGreaterThanOrEqualTo(String value) {
            addCriterion("VALIDATEDATE >=", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateLessThan(String value) {
            addCriterion("VALIDATEDATE <", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateLessThanOrEqualTo(String value) {
            addCriterion("VALIDATEDATE <=", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateLike(String value) {
            addCriterion("VALIDATEDATE like", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateNotLike(String value) {
            addCriterion("VALIDATEDATE not like", value, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateIn(List<String> values) {
            addCriterion("VALIDATEDATE in", values, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateNotIn(List<String> values) {
            addCriterion("VALIDATEDATE not in", values, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateBetween(String value1, String value2) {
            addCriterion("VALIDATEDATE between", value1, value2, "validatedate");
            return (Criteria) this;
        }

        public Criteria andValidatedateNotBetween(String value1, String value2) {
            addCriterion("VALIDATEDATE not between", value1, value2, "validatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateIsNull() {
            addCriterion("INVALIDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateIsNotNull() {
            addCriterion("INVALIDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateEqualTo(String value) {
            addCriterion("INVALIDATEDATE =", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateNotEqualTo(String value) {
            addCriterion("INVALIDATEDATE <>", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateGreaterThan(String value) {
            addCriterion("INVALIDATEDATE >", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateGreaterThanOrEqualTo(String value) {
            addCriterion("INVALIDATEDATE >=", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateLessThan(String value) {
            addCriterion("INVALIDATEDATE <", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateLessThanOrEqualTo(String value) {
            addCriterion("INVALIDATEDATE <=", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateLike(String value) {
            addCriterion("INVALIDATEDATE like", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateNotLike(String value) {
            addCriterion("INVALIDATEDATE not like", value, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateIn(List<String> values) {
            addCriterion("INVALIDATEDATE in", values, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateNotIn(List<String> values) {
            addCriterion("INVALIDATEDATE not in", values, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateBetween(String value1, String value2) {
            addCriterion("INVALIDATEDATE between", value1, value2, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andInvalidatedateNotBetween(String value1, String value2) {
            addCriterion("INVALIDATEDATE not between", value1, value2, "invalidatedate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(String value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(String value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(String value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(String value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(String value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLike(String value) {
            addCriterion("CREATEDATE like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotLike(String value) {
            addCriterion("CREATEDATE not like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<String> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<String> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(String value1, String value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(String value1, String value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(String value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(String value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(String value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(String value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(String value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLike(String value) {
            addCriterion("MODIFYDATE like", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotLike(String value) {
            addCriterion("MODIFYDATE not like", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<String> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<String> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(String value1, String value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(String value1, String value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(String value) {
            addCriterion("FLAG =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(String value) {
            addCriterion("FLAG <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(String value) {
            addCriterion("FLAG >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(String value) {
            addCriterion("FLAG >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(String value) {
            addCriterion("FLAG <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(String value) {
            addCriterion("FLAG <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLike(String value) {
            addCriterion("FLAG like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotLike(String value) {
            addCriterion("FLAG not like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<String> values) {
            addCriterion("FLAG in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<String> values) {
            addCriterion("FLAG not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(String value1, String value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(String value1, String value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyIsNull() {
            addCriterion("UNIONORGKEY is null");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyIsNotNull() {
            addCriterion("UNIONORGKEY is not null");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyEqualTo(String value) {
            addCriterion("UNIONORGKEY =", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyNotEqualTo(String value) {
            addCriterion("UNIONORGKEY <>", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyGreaterThan(String value) {
            addCriterion("UNIONORGKEY >", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyGreaterThanOrEqualTo(String value) {
            addCriterion("UNIONORGKEY >=", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyLessThan(String value) {
            addCriterion("UNIONORGKEY <", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyLessThanOrEqualTo(String value) {
            addCriterion("UNIONORGKEY <=", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyLike(String value) {
            addCriterion("UNIONORGKEY like", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyNotLike(String value) {
            addCriterion("UNIONORGKEY not like", value, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyIn(List<String> values) {
            addCriterion("UNIONORGKEY in", values, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyNotIn(List<String> values) {
            addCriterion("UNIONORGKEY not in", values, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyBetween(String value1, String value2) {
            addCriterion("UNIONORGKEY between", value1, value2, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andUnionorgkeyNotBetween(String value1, String value2) {
            addCriterion("UNIONORGKEY not between", value1, value2, "unionorgkey");
            return (Criteria) this;
        }

        public Criteria andOrgAreaIsNull() {
            addCriterion("ORG_AREA is null");
            return (Criteria) this;
        }

        public Criteria andOrgAreaIsNotNull() {
            addCriterion("ORG_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andOrgAreaEqualTo(String value) {
            addCriterion("ORG_AREA =", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaNotEqualTo(String value) {
            addCriterion("ORG_AREA <>", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaGreaterThan(String value) {
            addCriterion("ORG_AREA >", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_AREA >=", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaLessThan(String value) {
            addCriterion("ORG_AREA <", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaLessThanOrEqualTo(String value) {
            addCriterion("ORG_AREA <=", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaLike(String value) {
            addCriterion("ORG_AREA like", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaNotLike(String value) {
            addCriterion("ORG_AREA not like", value, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaIn(List<String> values) {
            addCriterion("ORG_AREA in", values, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaNotIn(List<String> values) {
            addCriterion("ORG_AREA not in", values, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaBetween(String value1, String value2) {
            addCriterion("ORG_AREA between", value1, value2, "orgArea");
            return (Criteria) this;
        }

        public Criteria andOrgAreaNotBetween(String value1, String value2) {
            addCriterion("ORG_AREA not between", value1, value2, "orgArea");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyIsNull() {
            addCriterion("SETTLEORGKEY is null");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyIsNotNull() {
            addCriterion("SETTLEORGKEY is not null");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyEqualTo(String value) {
            addCriterion("SETTLEORGKEY =", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyNotEqualTo(String value) {
            addCriterion("SETTLEORGKEY <>", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyGreaterThan(String value) {
            addCriterion("SETTLEORGKEY >", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLEORGKEY >=", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyLessThan(String value) {
            addCriterion("SETTLEORGKEY <", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyLessThanOrEqualTo(String value) {
            addCriterion("SETTLEORGKEY <=", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyLike(String value) {
            addCriterion("SETTLEORGKEY like", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyNotLike(String value) {
            addCriterion("SETTLEORGKEY not like", value, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyIn(List<String> values) {
            addCriterion("SETTLEORGKEY in", values, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyNotIn(List<String> values) {
            addCriterion("SETTLEORGKEY not in", values, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyBetween(String value1, String value2) {
            addCriterion("SETTLEORGKEY between", value1, value2, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andSettleorgkeyNotBetween(String value1, String value2) {
            addCriterion("SETTLEORGKEY not between", value1, value2, "settleorgkey");
            return (Criteria) this;
        }

        public Criteria andPartyIdIsNull() {
            addCriterion("PARTY_ID is null");
            return (Criteria) this;
        }

        public Criteria andPartyIdIsNotNull() {
            addCriterion("PARTY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPartyIdEqualTo(String value) {
            addCriterion("PARTY_ID =", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotEqualTo(String value) {
            addCriterion("PARTY_ID <>", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdGreaterThan(String value) {
            addCriterion("PARTY_ID >", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARTY_ID >=", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdLessThan(String value) {
            addCriterion("PARTY_ID <", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdLessThanOrEqualTo(String value) {
            addCriterion("PARTY_ID <=", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdLike(String value) {
            addCriterion("PARTY_ID like", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotLike(String value) {
            addCriterion("PARTY_ID not like", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdIn(List<String> values) {
            addCriterion("PARTY_ID in", values, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotIn(List<String> values) {
            addCriterion("PARTY_ID not in", values, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdBetween(String value1, String value2) {
            addCriterion("PARTY_ID between", value1, value2, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotBetween(String value1, String value2) {
            addCriterion("PARTY_ID not between", value1, value2, "partyId");
            return (Criteria) this;
        }

        public Criteria andOrgancodeIsNull() {
            addCriterion("ORGANCODE is null");
            return (Criteria) this;
        }

        public Criteria andOrgancodeIsNotNull() {
            addCriterion("ORGANCODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgancodeEqualTo(String value) {
            addCriterion("ORGANCODE =", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeNotEqualTo(String value) {
            addCriterion("ORGANCODE <>", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeGreaterThan(String value) {
            addCriterion("ORGANCODE >", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANCODE >=", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeLessThan(String value) {
            addCriterion("ORGANCODE <", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeLessThanOrEqualTo(String value) {
            addCriterion("ORGANCODE <=", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeLike(String value) {
            addCriterion("ORGANCODE like", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeNotLike(String value) {
            addCriterion("ORGANCODE not like", value, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeIn(List<String> values) {
            addCriterion("ORGANCODE in", values, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeNotIn(List<String> values) {
            addCriterion("ORGANCODE not in", values, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeBetween(String value1, String value2) {
            addCriterion("ORGANCODE between", value1, value2, "organcode");
            return (Criteria) this;
        }

        public Criteria andOrgancodeNotBetween(String value1, String value2) {
            addCriterion("ORGANCODE not between", value1, value2, "organcode");
            return (Criteria) this;
        }

        public Criteria andOverareaIndIsNull() {
            addCriterion("OVERAREA_IND is null");
            return (Criteria) this;
        }

        public Criteria andOverareaIndIsNotNull() {
            addCriterion("OVERAREA_IND is not null");
            return (Criteria) this;
        }

        public Criteria andOverareaIndEqualTo(String value) {
            addCriterion("OVERAREA_IND =", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndNotEqualTo(String value) {
            addCriterion("OVERAREA_IND <>", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndGreaterThan(String value) {
            addCriterion("OVERAREA_IND >", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndGreaterThanOrEqualTo(String value) {
            addCriterion("OVERAREA_IND >=", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndLessThan(String value) {
            addCriterion("OVERAREA_IND <", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndLessThanOrEqualTo(String value) {
            addCriterion("OVERAREA_IND <=", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndLike(String value) {
            addCriterion("OVERAREA_IND like", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndNotLike(String value) {
            addCriterion("OVERAREA_IND not like", value, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndIn(List<String> values) {
            addCriterion("OVERAREA_IND in", values, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndNotIn(List<String> values) {
            addCriterion("OVERAREA_IND not in", values, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndBetween(String value1, String value2) {
            addCriterion("OVERAREA_IND between", value1, value2, "overareaInd");
            return (Criteria) this;
        }

        public Criteria andOverareaIndNotBetween(String value1, String value2) {
            addCriterion("OVERAREA_IND not between", value1, value2, "overareaInd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_ORGAN
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_ORGAN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}