package com.demo.aml.pojo;

public class T00RoleAuthKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_ROLE_AUTH.ROLEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String rolekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_ROLE_AUTH.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modulekey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_ROLE_AUTH.ROLEKEY
     *
     * @return the value of T00_ROLE_AUTH.ROLEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getRolekey() {
        return rolekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_ROLE_AUTH.ROLEKEY
     *
     * @param rolekey the value for T00_ROLE_AUTH.ROLEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setRolekey(String rolekey) {
        this.rolekey = rolekey == null ? null : rolekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_ROLE_AUTH.MODULEKEY
     *
     * @return the value of T00_ROLE_AUTH.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModulekey() {
        return modulekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_ROLE_AUTH.MODULEKEY
     *
     * @param modulekey the value for T00_ROLE_AUTH.MODULEKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModulekey(String modulekey) {
        this.modulekey = modulekey == null ? null : modulekey.trim();
    }
}