package com.demo.aml.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class T00SystemLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public T00SystemLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogkeyIsNull() {
            addCriterion("LOGKEY is null");
            return (Criteria) this;
        }

        public Criteria andLogkeyIsNotNull() {
            addCriterion("LOGKEY is not null");
            return (Criteria) this;
        }

        public Criteria andLogkeyEqualTo(String value) {
            addCriterion("LOGKEY =", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyNotEqualTo(String value) {
            addCriterion("LOGKEY <>", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyGreaterThan(String value) {
            addCriterion("LOGKEY >", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyGreaterThanOrEqualTo(String value) {
            addCriterion("LOGKEY >=", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyLessThan(String value) {
            addCriterion("LOGKEY <", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyLessThanOrEqualTo(String value) {
            addCriterion("LOGKEY <=", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyLike(String value) {
            addCriterion("LOGKEY like", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyNotLike(String value) {
            addCriterion("LOGKEY not like", value, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyIn(List<String> values) {
            addCriterion("LOGKEY in", values, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyNotIn(List<String> values) {
            addCriterion("LOGKEY not in", values, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyBetween(String value1, String value2) {
            addCriterion("LOGKEY between", value1, value2, "logkey");
            return (Criteria) this;
        }

        public Criteria andLogkeyNotBetween(String value1, String value2) {
            addCriterion("LOGKEY not between", value1, value2, "logkey");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("REALNAME is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("REALNAME is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("REALNAME =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("REALNAME <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("REALNAME >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("REALNAME >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("REALNAME <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("REALNAME <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("REALNAME like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("REALNAME not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("REALNAME in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("REALNAME not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("REALNAME between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("REALNAME not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRolekeyIsNull() {
            addCriterion("ROLEKEY is null");
            return (Criteria) this;
        }

        public Criteria andRolekeyIsNotNull() {
            addCriterion("ROLEKEY is not null");
            return (Criteria) this;
        }

        public Criteria andRolekeyEqualTo(String value) {
            addCriterion("ROLEKEY =", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyNotEqualTo(String value) {
            addCriterion("ROLEKEY <>", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyGreaterThan(String value) {
            addCriterion("ROLEKEY >", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEKEY >=", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyLessThan(String value) {
            addCriterion("ROLEKEY <", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyLessThanOrEqualTo(String value) {
            addCriterion("ROLEKEY <=", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyLike(String value) {
            addCriterion("ROLEKEY like", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyNotLike(String value) {
            addCriterion("ROLEKEY not like", value, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyIn(List<String> values) {
            addCriterion("ROLEKEY in", values, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyNotIn(List<String> values) {
            addCriterion("ROLEKEY not in", values, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyBetween(String value1, String value2) {
            addCriterion("ROLEKEY between", value1, value2, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolekeyNotBetween(String value1, String value2) {
            addCriterion("ROLEKEY not between", value1, value2, "rolekey");
            return (Criteria) this;
        }

        public Criteria andRolenameIsNull() {
            addCriterion("ROLENAME is null");
            return (Criteria) this;
        }

        public Criteria andRolenameIsNotNull() {
            addCriterion("ROLENAME is not null");
            return (Criteria) this;
        }

        public Criteria andRolenameEqualTo(String value) {
            addCriterion("ROLENAME =", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotEqualTo(String value) {
            addCriterion("ROLENAME <>", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThan(String value) {
            addCriterion("ROLENAME >", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThanOrEqualTo(String value) {
            addCriterion("ROLENAME >=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThan(String value) {
            addCriterion("ROLENAME <", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThanOrEqualTo(String value) {
            addCriterion("ROLENAME <=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLike(String value) {
            addCriterion("ROLENAME like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotLike(String value) {
            addCriterion("ROLENAME not like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameIn(List<String> values) {
            addCriterion("ROLENAME in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotIn(List<String> values) {
            addCriterion("ROLENAME not in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameBetween(String value1, String value2) {
            addCriterion("ROLENAME between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotBetween(String value1, String value2) {
            addCriterion("ROLENAME not between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andGroupkeyIsNull() {
            addCriterion("GROUPKEY is null");
            return (Criteria) this;
        }

        public Criteria andGroupkeyIsNotNull() {
            addCriterion("GROUPKEY is not null");
            return (Criteria) this;
        }

        public Criteria andGroupkeyEqualTo(String value) {
            addCriterion("GROUPKEY =", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyNotEqualTo(String value) {
            addCriterion("GROUPKEY <>", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyGreaterThan(String value) {
            addCriterion("GROUPKEY >", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyGreaterThanOrEqualTo(String value) {
            addCriterion("GROUPKEY >=", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyLessThan(String value) {
            addCriterion("GROUPKEY <", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyLessThanOrEqualTo(String value) {
            addCriterion("GROUPKEY <=", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyLike(String value) {
            addCriterion("GROUPKEY like", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyNotLike(String value) {
            addCriterion("GROUPKEY not like", value, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyIn(List<String> values) {
            addCriterion("GROUPKEY in", values, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyNotIn(List<String> values) {
            addCriterion("GROUPKEY not in", values, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyBetween(String value1, String value2) {
            addCriterion("GROUPKEY between", value1, value2, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupkeyNotBetween(String value1, String value2) {
            addCriterion("GROUPKEY not between", value1, value2, "groupkey");
            return (Criteria) this;
        }

        public Criteria andGroupnameIsNull() {
            addCriterion("GROUPNAME is null");
            return (Criteria) this;
        }

        public Criteria andGroupnameIsNotNull() {
            addCriterion("GROUPNAME is not null");
            return (Criteria) this;
        }

        public Criteria andGroupnameEqualTo(String value) {
            addCriterion("GROUPNAME =", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotEqualTo(String value) {
            addCriterion("GROUPNAME <>", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameGreaterThan(String value) {
            addCriterion("GROUPNAME >", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameGreaterThanOrEqualTo(String value) {
            addCriterion("GROUPNAME >=", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLessThan(String value) {
            addCriterion("GROUPNAME <", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLessThanOrEqualTo(String value) {
            addCriterion("GROUPNAME <=", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLike(String value) {
            addCriterion("GROUPNAME like", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotLike(String value) {
            addCriterion("GROUPNAME not like", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameIn(List<String> values) {
            addCriterion("GROUPNAME in", values, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotIn(List<String> values) {
            addCriterion("GROUPNAME not in", values, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameBetween(String value1, String value2) {
            addCriterion("GROUPNAME between", value1, value2, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotBetween(String value1, String value2) {
            addCriterion("GROUPNAME not between", value1, value2, "groupname");
            return (Criteria) this;
        }

        public Criteria andIpaddressIsNull() {
            addCriterion("IPADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andIpaddressIsNotNull() {
            addCriterion("IPADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andIpaddressEqualTo(String value) {
            addCriterion("IPADDRESS =", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotEqualTo(String value) {
            addCriterion("IPADDRESS <>", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressGreaterThan(String value) {
            addCriterion("IPADDRESS >", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressGreaterThanOrEqualTo(String value) {
            addCriterion("IPADDRESS >=", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressLessThan(String value) {
            addCriterion("IPADDRESS <", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressLessThanOrEqualTo(String value) {
            addCriterion("IPADDRESS <=", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressLike(String value) {
            addCriterion("IPADDRESS like", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotLike(String value) {
            addCriterion("IPADDRESS not like", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressIn(List<String> values) {
            addCriterion("IPADDRESS in", values, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotIn(List<String> values) {
            addCriterion("IPADDRESS not in", values, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressBetween(String value1, String value2) {
            addCriterion("IPADDRESS between", value1, value2, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotBetween(String value1, String value2) {
            addCriterion("IPADDRESS not between", value1, value2, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andActionflagIsNull() {
            addCriterion("ACTIONFLAG is null");
            return (Criteria) this;
        }

        public Criteria andActionflagIsNotNull() {
            addCriterion("ACTIONFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andActionflagEqualTo(String value) {
            addCriterion("ACTIONFLAG =", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagNotEqualTo(String value) {
            addCriterion("ACTIONFLAG <>", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagGreaterThan(String value) {
            addCriterion("ACTIONFLAG >", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIONFLAG >=", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagLessThan(String value) {
            addCriterion("ACTIONFLAG <", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagLessThanOrEqualTo(String value) {
            addCriterion("ACTIONFLAG <=", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagLike(String value) {
            addCriterion("ACTIONFLAG like", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagNotLike(String value) {
            addCriterion("ACTIONFLAG not like", value, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagIn(List<String> values) {
            addCriterion("ACTIONFLAG in", values, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagNotIn(List<String> values) {
            addCriterion("ACTIONFLAG not in", values, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagBetween(String value1, String value2) {
            addCriterion("ACTIONFLAG between", value1, value2, "actionflag");
            return (Criteria) this;
        }

        public Criteria andActionflagNotBetween(String value1, String value2) {
            addCriterion("ACTIONFLAG not between", value1, value2, "actionflag");
            return (Criteria) this;
        }

        public Criteria andModulekeyIsNull() {
            addCriterion("MODULEKEY is null");
            return (Criteria) this;
        }

        public Criteria andModulekeyIsNotNull() {
            addCriterion("MODULEKEY is not null");
            return (Criteria) this;
        }

        public Criteria andModulekeyEqualTo(String value) {
            addCriterion("MODULEKEY =", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyNotEqualTo(String value) {
            addCriterion("MODULEKEY <>", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyGreaterThan(String value) {
            addCriterion("MODULEKEY >", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyGreaterThanOrEqualTo(String value) {
            addCriterion("MODULEKEY >=", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyLessThan(String value) {
            addCriterion("MODULEKEY <", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyLessThanOrEqualTo(String value) {
            addCriterion("MODULEKEY <=", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyLike(String value) {
            addCriterion("MODULEKEY like", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyNotLike(String value) {
            addCriterion("MODULEKEY not like", value, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyIn(List<String> values) {
            addCriterion("MODULEKEY in", values, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyNotIn(List<String> values) {
            addCriterion("MODULEKEY not in", values, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyBetween(String value1, String value2) {
            addCriterion("MODULEKEY between", value1, value2, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulekeyNotBetween(String value1, String value2) {
            addCriterion("MODULEKEY not between", value1, value2, "modulekey");
            return (Criteria) this;
        }

        public Criteria andModulenameIsNull() {
            addCriterion("MODULENAME is null");
            return (Criteria) this;
        }

        public Criteria andModulenameIsNotNull() {
            addCriterion("MODULENAME is not null");
            return (Criteria) this;
        }

        public Criteria andModulenameEqualTo(String value) {
            addCriterion("MODULENAME =", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotEqualTo(String value) {
            addCriterion("MODULENAME <>", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameGreaterThan(String value) {
            addCriterion("MODULENAME >", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameGreaterThanOrEqualTo(String value) {
            addCriterion("MODULENAME >=", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLessThan(String value) {
            addCriterion("MODULENAME <", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLessThanOrEqualTo(String value) {
            addCriterion("MODULENAME <=", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLike(String value) {
            addCriterion("MODULENAME like", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotLike(String value) {
            addCriterion("MODULENAME not like", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameIn(List<String> values) {
            addCriterion("MODULENAME in", values, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotIn(List<String> values) {
            addCriterion("MODULENAME not in", values, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameBetween(String value1, String value2) {
            addCriterion("MODULENAME between", value1, value2, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotBetween(String value1, String value2) {
            addCriterion("MODULENAME not between", value1, value2, "modulename");
            return (Criteria) this;
        }

        public Criteria andSystemkeyIsNull() {
            addCriterion("SYSTEMKEY is null");
            return (Criteria) this;
        }

        public Criteria andSystemkeyIsNotNull() {
            addCriterion("SYSTEMKEY is not null");
            return (Criteria) this;
        }

        public Criteria andSystemkeyEqualTo(String value) {
            addCriterion("SYSTEMKEY =", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyNotEqualTo(String value) {
            addCriterion("SYSTEMKEY <>", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyGreaterThan(String value) {
            addCriterion("SYSTEMKEY >", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMKEY >=", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyLessThan(String value) {
            addCriterion("SYSTEMKEY <", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMKEY <=", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyLike(String value) {
            addCriterion("SYSTEMKEY like", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyNotLike(String value) {
            addCriterion("SYSTEMKEY not like", value, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyIn(List<String> values) {
            addCriterion("SYSTEMKEY in", values, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyNotIn(List<String> values) {
            addCriterion("SYSTEMKEY not in", values, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyBetween(String value1, String value2) {
            addCriterion("SYSTEMKEY between", value1, value2, "systemkey");
            return (Criteria) this;
        }

        public Criteria andSystemkeyNotBetween(String value1, String value2) {
            addCriterion("SYSTEMKEY not between", value1, value2, "systemkey");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T00_SYSTEM_LOG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}