package com.demo.aml.pojo;

public class T00User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.REALNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.PASSWORD
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.ORGANKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String organkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.ISBUILDIN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String isbuildin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.ISADMIN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String isadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.ADDRESS
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.POSTALCODE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String postalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.EMAILADDRESS
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String emailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.TELEPHONE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.MOBILEPHONE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.DES
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.SEX
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.BIRTH
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.EDUCATION
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.ISNEWUSER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String isnewuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.POSITION
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.POSTITLE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String postitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.WORKLEVEL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String worklevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.POLITICAL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String political;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.INDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.STAFCODE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String stafcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.REMARK
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.DEFGROUPKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String defgroupkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.CURR_CD
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String currCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T00_USER.COLOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.USERNAME
     *
     * @return the value of T00_USER.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.USERNAME
     *
     * @param username the value for T00_USER.USERNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.REALNAME
     *
     * @return the value of T00_USER.REALNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.REALNAME
     *
     * @param realname the value for T00_USER.REALNAME
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.PASSWORD
     *
     * @return the value of T00_USER.PASSWORD
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.PASSWORD
     *
     * @param password the value for T00_USER.PASSWORD
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.ORGANKEY
     *
     * @return the value of T00_USER.ORGANKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOrgankey() {
        return organkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.ORGANKEY
     *
     * @param organkey the value for T00_USER.ORGANKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOrgankey(String organkey) {
        this.organkey = organkey == null ? null : organkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.FLAG
     *
     * @return the value of T00_USER.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.FLAG
     *
     * @param flag the value for T00_USER.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.ISBUILDIN
     *
     * @return the value of T00_USER.ISBUILDIN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getIsbuildin() {
        return isbuildin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.ISBUILDIN
     *
     * @param isbuildin the value for T00_USER.ISBUILDIN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setIsbuildin(String isbuildin) {
        this.isbuildin = isbuildin == null ? null : isbuildin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.ISADMIN
     *
     * @return the value of T00_USER.ISADMIN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.ISADMIN
     *
     * @param isadmin the value for T00_USER.ISADMIN
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setIsadmin(String isadmin) {
        this.isadmin = isadmin == null ? null : isadmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.ADDRESS
     *
     * @return the value of T00_USER.ADDRESS
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.ADDRESS
     *
     * @param address the value for T00_USER.ADDRESS
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.POSTALCODE
     *
     * @return the value of T00_USER.POSTALCODE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.POSTALCODE
     *
     * @param postalcode the value for T00_USER.POSTALCODE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.EMAILADDRESS
     *
     * @return the value of T00_USER.EMAILADDRESS
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.EMAILADDRESS
     *
     * @param emailaddress the value for T00_USER.EMAILADDRESS
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress == null ? null : emailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.TELEPHONE
     *
     * @return the value of T00_USER.TELEPHONE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.TELEPHONE
     *
     * @param telephone the value for T00_USER.TELEPHONE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.MOBILEPHONE
     *
     * @return the value of T00_USER.MOBILEPHONE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.MOBILEPHONE
     *
     * @param mobilephone the value for T00_USER.MOBILEPHONE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.DES
     *
     * @return the value of T00_USER.DES
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.DES
     *
     * @param des the value for T00_USER.DES
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.SEX
     *
     * @return the value of T00_USER.SEX
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.SEX
     *
     * @param sex the value for T00_USER.SEX
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.BIRTH
     *
     * @return the value of T00_USER.BIRTH
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.BIRTH
     *
     * @param birth the value for T00_USER.BIRTH
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.EDUCATION
     *
     * @return the value of T00_USER.EDUCATION
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.EDUCATION
     *
     * @param education the value for T00_USER.EDUCATION
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.ISNEWUSER
     *
     * @return the value of T00_USER.ISNEWUSER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getIsnewuser() {
        return isnewuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.ISNEWUSER
     *
     * @param isnewuser the value for T00_USER.ISNEWUSER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setIsnewuser(String isnewuser) {
        this.isnewuser = isnewuser == null ? null : isnewuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.POSITION
     *
     * @return the value of T00_USER.POSITION
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.POSITION
     *
     * @param position the value for T00_USER.POSITION
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.POSTITLE
     *
     * @return the value of T00_USER.POSTITLE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getPostitle() {
        return postitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.POSTITLE
     *
     * @param postitle the value for T00_USER.POSTITLE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setPostitle(String postitle) {
        this.postitle = postitle == null ? null : postitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.WORKLEVEL
     *
     * @return the value of T00_USER.WORKLEVEL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getWorklevel() {
        return worklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.WORKLEVEL
     *
     * @param worklevel the value for T00_USER.WORKLEVEL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setWorklevel(String worklevel) {
        this.worklevel = worklevel == null ? null : worklevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.POLITICAL
     *
     * @return the value of T00_USER.POLITICAL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.POLITICAL
     *
     * @param political the value for T00_USER.POLITICAL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setPolitical(String political) {
        this.political = political == null ? null : political.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.INDATE
     *
     * @return the value of T00_USER.INDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.INDATE
     *
     * @param indate the value for T00_USER.INDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setIndate(String indate) {
        this.indate = indate == null ? null : indate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.STAFCODE
     *
     * @return the value of T00_USER.STAFCODE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getStafcode() {
        return stafcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.STAFCODE
     *
     * @param stafcode the value for T00_USER.STAFCODE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setStafcode(String stafcode) {
        this.stafcode = stafcode == null ? null : stafcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.REMARK
     *
     * @return the value of T00_USER.REMARK
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.REMARK
     *
     * @param remark the value for T00_USER.REMARK
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.CREATEDATE
     *
     * @return the value of T00_USER.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.CREATEDATE
     *
     * @param createdate the value for T00_USER.CREATEDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.CREATOR
     *
     * @return the value of T00_USER.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.CREATOR
     *
     * @param creator the value for T00_USER.CREATOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.MODIFYDATE
     *
     * @return the value of T00_USER.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.MODIFYDATE
     *
     * @param modifydate the value for T00_USER.MODIFYDATE
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModifydate(String modifydate) {
        this.modifydate = modifydate == null ? null : modifydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.MODIFIER
     *
     * @return the value of T00_USER.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.MODIFIER
     *
     * @param modifier the value for T00_USER.MODIFIER
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.DEFGROUPKEY
     *
     * @return the value of T00_USER.DEFGROUPKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getDefgroupkey() {
        return defgroupkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.DEFGROUPKEY
     *
     * @param defgroupkey the value for T00_USER.DEFGROUPKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setDefgroupkey(String defgroupkey) {
        this.defgroupkey = defgroupkey == null ? null : defgroupkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.CURR_CD
     *
     * @return the value of T00_USER.CURR_CD
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getCurrCd() {
        return currCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.CURR_CD
     *
     * @param currCd the value for T00_USER.CURR_CD
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setCurrCd(String currCd) {
        this.currCd = currCd == null ? null : currCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T00_USER.COLOR
     *
     * @return the value of T00_USER.COLOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T00_USER.COLOR
     *
     * @param color the value for T00_USER.COLOR
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }
}