package com.demo.aml.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class T87OrganMapExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public T87OrganMapExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrgankeyIsNull() {
            addCriterion("ORGANKEY is null");
            return (Criteria) this;
        }

        public Criteria andOrgankeyIsNotNull() {
            addCriterion("ORGANKEY is not null");
            return (Criteria) this;
        }

        public Criteria andOrgankeyEqualTo(String value) {
            addCriterion("ORGANKEY =", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotEqualTo(String value) {
            addCriterion("ORGANKEY <>", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyGreaterThan(String value) {
            addCriterion("ORGANKEY >", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANKEY >=", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyLessThan(String value) {
            addCriterion("ORGANKEY <", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyLessThanOrEqualTo(String value) {
            addCriterion("ORGANKEY <=", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyLike(String value) {
            addCriterion("ORGANKEY like", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotLike(String value) {
            addCriterion("ORGANKEY not like", value, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyIn(List<String> values) {
            addCriterion("ORGANKEY in", values, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotIn(List<String> values) {
            addCriterion("ORGANKEY not in", values, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyBetween(String value1, String value2) {
            addCriterion("ORGANKEY between", value1, value2, "organkey");
            return (Criteria) this;
        }

        public Criteria andOrgankeyNotBetween(String value1, String value2) {
            addCriterion("ORGANKEY not between", value1, value2, "organkey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyIsNull() {
            addCriterion("SUBORGANKEY is null");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyIsNotNull() {
            addCriterion("SUBORGANKEY is not null");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyEqualTo(String value) {
            addCriterion("SUBORGANKEY =", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyNotEqualTo(String value) {
            addCriterion("SUBORGANKEY <>", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyGreaterThan(String value) {
            addCriterion("SUBORGANKEY >", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyGreaterThanOrEqualTo(String value) {
            addCriterion("SUBORGANKEY >=", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyLessThan(String value) {
            addCriterion("SUBORGANKEY <", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyLessThanOrEqualTo(String value) {
            addCriterion("SUBORGANKEY <=", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyLike(String value) {
            addCriterion("SUBORGANKEY like", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyNotLike(String value) {
            addCriterion("SUBORGANKEY not like", value, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyIn(List<String> values) {
            addCriterion("SUBORGANKEY in", values, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyNotIn(List<String> values) {
            addCriterion("SUBORGANKEY not in", values, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyBetween(String value1, String value2) {
            addCriterion("SUBORGANKEY between", value1, value2, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andSuborgankeyNotBetween(String value1, String value2) {
            addCriterion("SUBORGANKEY not between", value1, value2, "suborgankey");
            return (Criteria) this;
        }

        public Criteria andOrganlevelIsNull() {
            addCriterion("ORGANLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andOrganlevelIsNotNull() {
            addCriterion("ORGANLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andOrganlevelEqualTo(String value) {
            addCriterion("ORGANLEVEL =", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotEqualTo(String value) {
            addCriterion("ORGANLEVEL <>", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelGreaterThan(String value) {
            addCriterion("ORGANLEVEL >", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANLEVEL >=", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelLessThan(String value) {
            addCriterion("ORGANLEVEL <", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelLessThanOrEqualTo(String value) {
            addCriterion("ORGANLEVEL <=", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelLike(String value) {
            addCriterion("ORGANLEVEL like", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotLike(String value) {
            addCriterion("ORGANLEVEL not like", value, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelIn(List<String> values) {
            addCriterion("ORGANLEVEL in", values, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotIn(List<String> values) {
            addCriterion("ORGANLEVEL not in", values, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelBetween(String value1, String value2) {
            addCriterion("ORGANLEVEL between", value1, value2, "organlevel");
            return (Criteria) this;
        }

        public Criteria andOrganlevelNotBetween(String value1, String value2) {
            addCriterion("ORGANLEVEL not between", value1, value2, "organlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelIsNull() {
            addCriterion("SUBORGANLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelIsNotNull() {
            addCriterion("SUBORGANLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelEqualTo(String value) {
            addCriterion("SUBORGANLEVEL =", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelNotEqualTo(String value) {
            addCriterion("SUBORGANLEVEL <>", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelGreaterThan(String value) {
            addCriterion("SUBORGANLEVEL >", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelGreaterThanOrEqualTo(String value) {
            addCriterion("SUBORGANLEVEL >=", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelLessThan(String value) {
            addCriterion("SUBORGANLEVEL <", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelLessThanOrEqualTo(String value) {
            addCriterion("SUBORGANLEVEL <=", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelLike(String value) {
            addCriterion("SUBORGANLEVEL like", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelNotLike(String value) {
            addCriterion("SUBORGANLEVEL not like", value, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelIn(List<String> values) {
            addCriterion("SUBORGANLEVEL in", values, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelNotIn(List<String> values) {
            addCriterion("SUBORGANLEVEL not in", values, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelBetween(String value1, String value2) {
            addCriterion("SUBORGANLEVEL between", value1, value2, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andSuborganlevelNotBetween(String value1, String value2) {
            addCriterion("SUBORGANLEVEL not between", value1, value2, "suborganlevel");
            return (Criteria) this;
        }

        public Criteria andCallayerIsNull() {
            addCriterion("CALLAYER is null");
            return (Criteria) this;
        }

        public Criteria andCallayerIsNotNull() {
            addCriterion("CALLAYER is not null");
            return (Criteria) this;
        }

        public Criteria andCallayerEqualTo(String value) {
            addCriterion("CALLAYER =", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerNotEqualTo(String value) {
            addCriterion("CALLAYER <>", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerGreaterThan(String value) {
            addCriterion("CALLAYER >", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerGreaterThanOrEqualTo(String value) {
            addCriterion("CALLAYER >=", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerLessThan(String value) {
            addCriterion("CALLAYER <", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerLessThanOrEqualTo(String value) {
            addCriterion("CALLAYER <=", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerLike(String value) {
            addCriterion("CALLAYER like", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerNotLike(String value) {
            addCriterion("CALLAYER not like", value, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerIn(List<String> values) {
            addCriterion("CALLAYER in", values, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerNotIn(List<String> values) {
            addCriterion("CALLAYER not in", values, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerBetween(String value1, String value2) {
            addCriterion("CALLAYER between", value1, value2, "callayer");
            return (Criteria) this;
        }

        public Criteria andCallayerNotBetween(String value1, String value2) {
            addCriterion("CALLAYER not between", value1, value2, "callayer");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNull() {
            addCriterion("CREATE_DT is null");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNotNull() {
            addCriterion("CREATE_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDtEqualTo(Date value) {
            addCriterion("CREATE_DT =", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotEqualTo(Date value) {
            addCriterion("CREATE_DT <>", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThan(Date value) {
            addCriterion("CREATE_DT >", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DT >=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThan(Date value) {
            addCriterion("CREATE_DT <", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DT <=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtIn(List<Date> values) {
            addCriterion("CREATE_DT in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotIn(List<Date> values) {
            addCriterion("CREATE_DT not in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtBetween(Date value1, Date value2) {
            addCriterion("CREATE_DT between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DT not between", value1, value2, "createDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T87_ORGAN_MAP
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}