package com.demo.aml.pojo;

public class T87Syspara {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T87_SYSPARA.PARAKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String parakey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T87_SYSPARA.PARADES
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String parades;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T87_SYSPARA.PARAVAL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String paraval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T87_SYSPARA.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T87_SYSPARA.PARAKEY
     *
     * @return the value of T87_SYSPARA.PARAKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getParakey() {
        return parakey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T87_SYSPARA.PARAKEY
     *
     * @param parakey the value for T87_SYSPARA.PARAKEY
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setParakey(String parakey) {
        this.parakey = parakey == null ? null : parakey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T87_SYSPARA.PARADES
     *
     * @return the value of T87_SYSPARA.PARADES
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getParades() {
        return parades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T87_SYSPARA.PARADES
     *
     * @param parades the value for T87_SYSPARA.PARADES
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setParades(String parades) {
        this.parades = parades == null ? null : parades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T87_SYSPARA.PARAVAL
     *
     * @return the value of T87_SYSPARA.PARAVAL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getParaval() {
        return paraval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T87_SYSPARA.PARAVAL
     *
     * @param paraval the value for T87_SYSPARA.PARAVAL
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setParaval(String paraval) {
        this.paraval = paraval == null ? null : paraval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T87_SYSPARA.FLAG
     *
     * @return the value of T87_SYSPARA.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T87_SYSPARA.FLAG
     *
     * @param flag the value for T87_SYSPARA.FLAG
     *
     * @mbg.generated Mon Apr 09 14:51:59 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }
}